import json
import socket
import datetime
from ping import do_one as ping

TIMEOUT = 2
COUNT = 4
PSIZE = 64

def check(ip):
    success_ping = 0
    delay = 0
    for i in xrange(COUNT):
        try:
            d = ping(ip, TIMEOUT, PSIZE)
            if d is not None:
                delay += d
                success_ping += 1
        except socket.gaierror:
            # todo: log error
            return False, "error"
        except socket.error:
            return False, "down"
    if success_ping == 0:
        return False, "down"
    return True, '{:0.4f}ms'.format((delay * 1000 / success_ping))

def main():
    res = {}
    with open('./resources.json') as res_f:
        res = json.load(res_f)

    gen = []
    gen.append('{:^84}'.format('Camping Punta Indiani snc :: status page'))
    start_time = datetime.datetime.utcnow()
    for g_name, rs in res.items():
        gen.append('{}'.format(g_name.upper()))
        for r in rs:
            ok, res = check(r['ip'])
            gen.append('{:<10}{:<10}{:<30}{:>20} -> {:>10}'.format(
                '',
                'SUCCESS' if ok else "FAILED", 
                r['name'], 
                r['ip'], 
                res)) 

    end_time = datetime.datetime.utcnow()

    gen.append('')
    gen.append('Start  time {:>72}'.format(str(start_time)))
    gen.append('Finish time {:>72}'.format(str(end_time)))
    gen.append('')
    gen.append('Generated by {:>71}'.format(
        'https://github.com/MartinBrugnara/status'))
    gen.append('')

    with open('./status.txt', 'w+') as out_f:
        out_f.write('\n\r'.join(gen))

if __name__ == '__main__':
    main()
